### ISSUE TITLE
ndk compile error

### ISSUE THREAD

**Issue by 107295472** [dart-sys/dart-sys#57]
warning: INFO: build log is located at: `D:\flutter\my_app\rust\target\aarch64-linux-android\release\build\dart-sys-bc658e4de279a038\out\build.log`

error: failed to run custom build command for `dart-sys v3.1.12`

Caused by:
  process didn't exit successfully: `D:\flutter\my_app\rust\target\release\build\dart-sys-8d94e9c5e33b0ad6\build-script-build` (exit code: 101)
  --- stdout
  cargo:warning=INFO: build log is located at: `D:\flutter\my_app\rust\target\aarch64-linux-android\release\build\dart-sys-bc658e4de279a038\out\build.log`

  --- stderr
  C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\dart-sys-3.1.12\dart-sdk\include/dart_api.h:24:10: fatal error: 'assert.h' file not found
  thread 'main' panicked at 'ERROR: Failed to generate dart_api_dl binding: ClangDiagnostic("C:\\Users\\Administrator\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\dart-sys-3.1.12\\dart-sdk\\include/dart_api.h:24:10: fatal error: 'assert.h' file not found\n")', C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\dart-sys-3.1.12\build.rs:666:10

**Comment by gutenfries** [comment]
## Hi! :wave:

Thanks for reporting this.

We are aware of the issues surrounding Dart-sys at the moment and are currently working on refactoring our codebase.
