### ISSUE TITLE
Repository Licensing

### ISSUE THREAD

**Issue by gutenfries** [dart-sys/dart-sys#6]
## Hi @OptimisticPeach! :wave:

The team over at https://github.com/fzyzcjy/flutter_rust_bridge is working on some improvements right now and we are interested in forking https://github.com/OptimisticPeach/dart-sys and integrating large portions of the crate directly into the codebase. 

related working PR: https://github.com/fzyzcjy/flutter_rust_bridge/pull/894

We noticed, however, that the licensing on this codebase is a little blurry, and we wish to respect your wishes regardless of what license is intended to be applied.

In the _crate's_ `Cargo.toml` https://github.com/OptimisticPeach/dart-sys/blob/master/Cargo.toml?#L12, the _crate_ is marked as MIT-licensed, however, there is no license file in either the _crate_ or the _repository_.

If you could provide some insight as to what your intended licensing and wishes for the codebase are, we would deeply appreciate that and be sure to respect your licensing/wishes.

Thanks!

/cc @fzyzcjy

**Comment by OptimisticPeach** [comment]
Hi there @gutenfries 😄 

I'd love to help sort out the issues with this repo, as well has helping with the other PR that's been opened. I've skimmed the linked issues and PRs, and I've got a few to say that could help.

Unfortunately this will probably have to wait till tomorrow afternoon or the day after -- I have an important final examination for a uni course which takes precedence over this. 

If I don't reply within the next 24 hours, send me a ping either here or on Discord somewhere (I am @OptimisticPeach there as well, and you can find me on the main and community rust servers as well as the gamedev in rust server).

Sorry for the inconvenience, but I'm glad to see someone taking interest in this ❤️

**Comment by fzyzcjy** [comment]
Take your time and wish you perform well in exams!

**Comment by OptimisticPeach** [comment]
Hi there!

So a few things to clear up:

- This repo is indeed under MIT (I had just not learnt that one needed to add an actual license file to the root of the repo for that to be valid). If necessary, I can push a commit with said license file if you'd rather have that security.
- If I recall correctly, the way I did the codegen was to use `bindgen` once and then tweak the bindings a bit, regenerating the bindings every time afterwards and applying the same changes.
  - This obviously didn't happen because I eventually became uninterested in Dart :(
- You are free to integrate the dart-sys crate into your own repo. If you so wish, once you have a working version to publish, I'd be happy to transfer the ownership of the crate on crates.io over to you guys.

Feel free to ping me anytime now as final exams are now complete for the term 😄,

**Comment by fzyzcjy** [comment]
> This repo is indeed under MIT (I had just not learnt that one needed to add an actual license file to the root of the repo for that to be valid). If necessary, I can push a commit with said license file if you'd rather have that security.

I also did not know it until someone told me ;) https://github.com/fzyzcjy/flutter_rust_bridge/issues/1

For the rest part, cc @gutenfries who initiated the integrate-dart-sys :)

**Comment by gutenfries** [comment]
@fzyzcjy, code-related topics aside, how do you want to go about integrating dart-sys?

On my machine I have a fork of https://github.com/fzyzcjy/flutter_rust_bridge

**Comment by gutenfries** [comment]
*excuse me I hit the wrong button 😅

**Comment by gutenfries** [comment]
@fzyzcjy, code-related topics aside for now, how do we want to go about integrating dart-sys?

I have some thoughts:

On my machine, I have a fork of https://github.com/fzyzcjy/flutter_rust_bridge that I've been using for development on my machine where I included `dart-sys` with generous changes at the root of the repo and used it as a cargo dependency in `FRB`. This is working well for me, BUT, I do not think that integrating the crate like this is sustainable.

IMHO, we should:

> You are free to integrate the dart-sys crate into your own repo. If you so wish, once you have a working version to publish, I'd be happy to transfer the ownership of the crate on crates.io over to you guys.

Transfer ownership of the repo to either my account, or your account, OR we could make a GH org and store the repo there, and possibly consider eventually moving https://github.com/fzyzcjy/flutter_rust_bridge to the org as well. If we do go this route, we should be sure to include @OptimisticPeach. :wink:

Just food for thought.

### Either way, **_we need to keep `dart-sys` independent of FRB_** because the use cases for the crate extend beyond our project.

We can version `dart-sys` through cargo like normal and there should not be any issues integrating it again.


@OptimisticPeach: know that no matter what we end up deciding on as far as details of management, maintenance, and ownership of `dart-sys`, know that you **will** be credited with co-ownership of the repository :)

and thank you again @OptimisticPeach for your cooperation and involvement in this, we really appreciate it!! :smile:

**Comment by gutenfries** [comment]
_\*excuse the verbose notifications..._

Another thought @fzyzcjy, we could also consider using a git submodule for `dart-sys`.

**Comment by OptimisticPeach** [comment]
> Transfer ownership of the repo to either my account, or your account, OR we could make a GH org and store the repo there, and possibly consider eventually moving https://github.com/fzyzcjy/flutter_rust_bridge to the org as well. If we do go this route, we should be sure to include @OptimisticPeach. 😉

This sounds like a great idea 👍. Once you've decided on what to do (and in what order to do it), let me know when my cue is.

> Either way, we need to keep dart-sys independent of FRB because the use cases for the crate extend beyond our project.

Actually, I've seen plenty of crates live inside of another unrelated repo, so it's not 100% necessary to do this. Sure, it does increase project complexity, and probably isn't worth it, but if you'd rather do it like this, then there are definitely ways of doing it like this.

> @OptimisticPeach: know that no matter what we end up deciding on as far as details of management, maintenance, and ownership of dart-sys, know that you will be credited with co-ownership of the repository :)

Thanks 😄, I'm glad to hear it. 

> and thank you again @OptimisticPeach for your cooperation and involvement in this, we really appreciate it!! 😄

Any time! Feel free to ping me with more questions or discussion.

**Comment by fzyzcjy** [comment]
I am OK with either approach about dart-sys, as long as the code quality is high and it is maintained well ;)

**Comment by gutenfries** [comment]
Apologies for ghosting, I have been out sick for the past few days :(

I am more than willing to maintain `dart-sys` and would be happy to do the work that needs to be done. 

> Actually, I've seen plenty of crates live inside of another unrelated repo, so it's not 100% necessary to do this. Sure, it does increase project complexity, and probably isn't worth it, but if you'd rather do it like this, then there are definitely ways of doing it like this.

As @\OptimisticPeach mentioned, it _is_ in fast possible to have a (published) crate live inside an unrelated repository, but IMO there is no reason for us to put `dart-sys` inside of FRB if we can maintain the codebase. We only looked into integrating it directly because `dart-sys` had been inactive for 3 years and getting it maintained seemed out of reach.

**Comment by fzyzcjy** [comment]
Sad to hear that and hope you recover quickly!

As for who and where maintain dart-sys, I am totally OK with all options. For example, one of the many possible ways is that, @gutenfries sends PR to @OptimisticPeach in dart-sys repo.

**Comment by gutenfries** [comment]
Hey sorry for falling off the face of the earth (again...), I've been on break for the holidays and have not been on GitHub.

@OptimisticPeach IMHO, there are three main options we have for the repository:

1) If you (@OptimisticPeach) are willing to maintain `dart-sys`, review PRs, manage CI/CD, etc. then I don't see any reason why we should transfer ownership of the repository.

If you are unable or unwilling to commit to that, that is OK, and in that case, we should consider one of the following:

2) We can create a GitHub organization and transfer ownership of the repository to the _organization_. This has the benefit of easily allowing multiple maintainers.

3) I can take on being the sole maintainer and review PRs, etc., and transfer `dart-sys` to my account.


## Regardless of what we do, remember the goal is CLEAN, MAINTAINABLE, and REPRODUCIBLE code.

**Comment by OptimisticPeach** [comment]
Hi there, no issue, everybody's busy nowadays :)

I'd be most comfortable with option 2, but otherwise option 3 works well too -- I'm not willing to commit time to reviewing PRs and issues for this repository (this was created as part of a one-off project a long time ago). 

When you've made a decision, let me know.

Have a happy new year! 🎉

**Comment by fzyzcjy** [comment]
Happy new year!

**Comment by gutenfries** [comment]
@OptimisticPeach check your inbox, I've created an organization we can get started on :)

**Comment by OptimisticPeach** [comment]
I do believe that it has been transferred 😄!

**Comment by gutenfries** [comment]
Awesome! :D 
Before Closing out this issue, I would like to make a linked PR which will add a `LICENSE.md` file, just to keep the licensing clear with the original authors :)

**Comment by OptimisticPeach** [comment]
Just sent a review, everything looks good to me!

**Comment by gutenfries** [comment]
closed by #7
